import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { iranPeyda } from "./fonts";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${iranPeyda.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
